[project]
name = "ops-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thorvald Molthe Ballestad", email = "thorvald@simula.no" }
]
requires-python = ">=3.14"
dependencies = [
    "requests==2.34.2",
]

[project.scripts]
ops-testing = "ops_testing:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
